MGMT-7957 - `test_kube_api` fix to use newer `ClusterConfig` members
openshift/assisted-test-infra pull request #1150
Opened 2021-10-13 10:10 UTC by omertuc

aec453f5fcf1da37e6171940df71fef1bc96cf66 changed the format of the `ClusterConfig`
class but forgot to update all usages of it.

For now this is a quick fix just to get the kube-api CI working again, it is
not an entirely correct fix because it has poor support for dual network stack
clusters.

This may be improved in future PRs

2021-10-13 10:39 UTC, omertuc commented
/cc @eliorerz @mkowalski

2021-10-13 16:48 UTC, omertuc commented on discovery-infra/test_infra/utils/global_variables/global_variables.py
> +            assert isinstance(conditions, tuple) and all(isinstance(condition, tuple)
this change is just some refactoring / cleaning up, no interesting bug fixes here

2021-10-13 17:37 UTC, eliorerz commented on discovery-infra/test_infra/utils/global_variables/global_variables.py
> +        (("is_ipv4", True), ("is_ipv6", False),): {
I think those are the default values, No?

2021-10-13 17:43 UTC, eliorerz commented on discovery-infra/tests/test_kube_api.py
> +        service_network=cluster_config.service_networks[0].cidr,
I think it is better to add getters on `cluster_config.py` and use them on all the other places:
e.g. 

```python
class BaseClusterConfig(BaseEntityConfig, ABC):
    ...

    @property
    def network_cidr(self):
        return self.cluster_networks[0].cidr if self.cluster_networks else None

    @property
    def network_host_prefix(self):
        return self.cluster_networks[0].host_prefix if self.cluster_networks else None

    @property
    def service_network_cidr(self):
        return self.service_networks[0].cidr if self.service_networks else None

```

2021-10-17 05:51 UTC, osherdp requested changes

2021-10-17 05:51 UTC, osherdp commented on discovery-infra/test_infra/utils/global_variables/global_variables.py
> +            "network_type": consts.NetworkType.OVNKubernetes
Isn't it a change from the previous default?

2021-10-17 12:48 UTC, osherdp approved these changes

2021-10-19 12:53 UTC, omertuc commented
/retest

2021-10-19 18:50 UTC, omertuc commented
\o/

2021-10-20 13:38 UTC, omertuc commented
/test lint

2021-10-20 14:04 UTC, eliorerz commented
/override ci/prow/lint

2021-10-20 14:06 UTC, omertuc commented
/unhold

2021-10-20 20:24 UTC, merged