Moving events to v2
openshift/assisted-test-infra pull request #1153
Opened 2021-10-14 13:56 UTC by iovadia

Signed-off-by: iovadia <iovadia@redhat.com>

/cc @osherdp @eliorerz @lalon4 @nshidlin

2021-10-16 04:47 UTC, eliorerz commented on discovery-infra/test_infra/helper_classes/cluster.py
> +    def _find_event(self, event_to_find, reference_time, params_list, host_id, infra_env_id):
Add type hint annotations and return type annotations

2021-10-16 04:47 UTC, eliorerz commented on discovery-infra/test_infra/helper_classes/cluster.py
> +    def wait_for_event(self, event_to_find, reference_time, params_list=None, host_id="",infra_env_id="", timeout=10):
Add type hint annotations

2021-10-16 04:47 UTC, eliorerz commented on discovery-infra/test_infra/helper_classes/cluster.py
> +    def get_events(self, host_id="", infra_env_id=""):
Add type hint annotations and return type annotations

2021-10-16 06:05 UTC, eliorerz commented
I'm not sure events should stay under `Cluster` ass it was before.
On v2 `events` endpoint moved to independent endpoint and no longer is under `cluster`.
I think we should create new object to handle the events.
@nmagnezi @tsorya @nshidlin WDYT?

2021-10-17 06:56 UTC, tsorya commented
> I'm not sure events should stay under `Cluster` as it was before. On v2 `events` endpoint moved to independent endpoint and it's no longer under `cluster`. I think we should create new object to handle the events.
> 
> e.g.
> 
> ```python
> class EventsHandler:
>     def __init__(self, api_client: InventoryClient, cluster_id: str, infra_env_id: str):
>         self.api_client = api_client
>         self.infra_env_id = infra_env_id
>         self.cluster_id = cluster_id
> 
>     def _find_event(self, event_to_find, reference_time, params_list, host_id):
>         ...
>     def get_events(self, host_id=""):
>         ...
> 
>     def wait_for_event(self, event_to_find, reference_time, params_list=None, host_id="", timeout=10):
>         ...
> ```
> 
> @nmagnezi @tsorya @nshidlin WDYT?

I don't think we need events out of the cluster scope so i don't see any reason to move 2 small api out of it right now

2021-10-17 07:27 UTC, nmagnezi requested changes
> I'm not sure events should stay under `Cluster` as it was before. On v2 `events` endpoint moved to independent endpoint and it's no longer under `cluster`. I think we should create new object to handle the events.
> 
> e.g.
> 
> ```python
> class EventsHandler:
>     def __init__(self, api_client: InventoryClient, cluster_id: str, infra_env_id: str):
>         self.api_client = api_client
>         self.infra_env_id = infra_env_id
>         self.cluster_id = cluster_id
> 
>     def _find_event(self, event_to_find, reference_time, params_list, host_id):
>         ...
>     def get_events(self, host_id=""):
>         ...
> 
>     def wait_for_event(self, event_to_find, reference_time, params_list=None, host_id="", timeout=10):
>         ...
> ```
> 
> @nmagnezi @tsorya @nshidlin WDYT?

IMO, you make a good point. In V1 all events had `cluster-id`, but now this is no longer the case. For example, host events that are linked to `infra_env`, but might not be bounded to a cluster at this point.

https://github.com/openshift/assisted-service/blob/cc39df66bb6431e7843d3be828fdc9e4a731939c/docs/events.yaml#L35-L41

2021-10-17 08:13 UTC, eliorerz commented
> In that case lets move them with another jira ticket. Right now there is no use of events without cluster id in the code. Lets finish this task and move them to new object when we will need it

OK,  don't think it requires much of a change but I opened a ticket for doing it https://issues.redhat.com/browse/MGMT-7977

2021-10-17 08:14 UTC, eliorerz approved these changes

2021-10-17 08:16 UTC, eliorerz commented
/unhold

2021-10-17 09:48 UTC, merged