Refactor/terraform to modules
openshift/assisted-test-infra pull request #1201
Opened 2021-10-31 15:26 UTC by osherdp

/cc @osherdp 
/hold

2021-10-31 15:27 UTC, osherdp commented
/test ?

2021-10-31 15:27 UTC, osherdp commented
/test e2e-metal-single-node-live-iso

2021-10-31 17:00 UTC, osherdp commented
/test e2e-metal-assisted-networking

2021-11-01 09:43 UTC, osherdp commented
/test e2e-metal-assisted-kube-api

2021-11-01 09:53 UTC, osherdp commented
/test e2e-metal-assisted-kube-api-late-binding-single-node

2021-11-01 13:50 UTC, osherdp commented
/test e2e-metal-assisted-kube-api-late-binding-single-node

2021-11-01 15:49 UTC, osherdp commented
/test e2e-metal-single-node-live-iso

2021-11-01 16:14 UTC, osherdp commented
/test e2e-metal-assisted-kube-api-late-binding-single-node

2021-11-01 17:50 UTC, osherdp commented
/retest

2021-11-01 19:00 UTC, osherdp commented
/test all

2021-11-01 19:03 UTC, osherdp commented
/test e2e-metal-assisted-none-ipv6
/test e2e-metal-assisted-olm
/test e2e-metal-assisted-single-node

2021-11-02 05:42 UTC, osherdp commented
/retest

2021-11-02 07:25 UTC, osherdp commented
/test e2e-metal-assisted-none-ipv6

2021-11-02 07:33 UTC, osherdp commented
/cc @eliorerz @tsorya @omertuc @rollandf 
hi guys, please review this work
mainly help me make sure the structure is still right for none-platform (@rollandf) and late-binding (@omertuc)

2021-11-02 08:13 UTC, osherdp commented
/test e2e-metal-assisted-none-ipv6
(known minikube's etcd problem)

2021-11-02 09:09 UTC, omertuc commented
/test system-test-operator

2021-11-02 12:42 UTC, tsorya commented
/lgtm

2021-11-02 14:33 UTC, osherdp commented
/test e2e-metal-assisted-none-ipv6
(just trying to understand if it's a flake)

2021-11-02 19:23 UTC, osherdp commented
/unhold

2021-11-02 21:05 UTC, eliorerz commented
/hold

2021-11-02 21:10 UTC, eliorerz requested changes

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/tools/static_network.py
> +    tfvars_json_file = os.path.join(tf_folder, "baremetal", consts.TFVARS_JSON_NAME)
```suggestion
    tfvars_json_file = os.path.join(tf_folder, consts.Platforms.BARE_METAL, consts.TFVARS_JSON_NAME)
```

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/tools/static_network.py
> +    tfvars_json_file = os.path.join(tf_folder, "baremetal", consts.TFVARS_JSON_NAME)
```suggestion
    tfvars_json_file = os.path.join(tf_folder, consts.Platforms.BARE_METAL, consts.TFVARS_JSON_NAME)
```

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/utils/kubeapi_utils.py
> +    baremetal_template = os.path.join(tf_folder, "baremetal")
consts.Platforms.BARE_METAL

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/utils/utils.py
> +def copy_template_tree(dst):
Add type annotations

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
> +            return os.path.join(tf_folder, "none")
```suggestion
            return os.path.join(tf_folder, consts.Platforms.NONE)
```

2021-11-02 21:10 UTC, eliorerz commented on discovery-infra/test_infra/controllers/node_controllers/terraform_controller.py
> +        return os.path.join(tf_folder, "baremetal")
```suggestion
        return os.path.join(tf_folder, consts.Platforms.BARE_METAL)
```

2021-11-02 21:21 UTC, osherdp commented
/unhold

2021-11-02 21:23 UTC, eliorerz approved these changes
LGTM

2021-11-02 22:24 UTC, osherdp commented
/override ci/prow/e2e-metal-assisted-none-ipv6
/override ci/prow/e2e-metal-assisted-networking
/override ci/prow/e2e-metal-assisted-ipv4v6

2021-11-02 22:26 UTC, osherdp commented
/override ci/prow/e2e-metal-assisted-networking
/override ci/prow/e2e-metal-assisted-ipv4v6

2021-11-03 00:31 UTC, merged