MGMT-8529 - Raise exception on ISO download failure
openshift/assisted-test-infra pull request #1296
Opened 2021-12-13 21:47 UTC by eliorerz

/cc @osherdp

2021-12-13 21:59 UTC, eliorerz commented
/test e2e-metal-assisted-kube-api

2021-12-14 09:11 UTC, osherdp requested changes

2021-12-14 09:11 UTC, osherdp commented on discovery-infra/test_infra/utils/utils.py
> +                raise HTTPError(f"Failed to download ISO from {url}, status_code={r.status_code}, {r.text}")
```suggestion
            r.raise_for_status()
```

2021-12-14 11:13 UTC, eliorerz commented on discovery-infra/test_infra/utils/utils.py
> +                raise HTTPError(f"Failed to download ISO from {url}, status_code={r.status_code}, {r.text}")
Nice.. Didn't knew that

2021-12-14 11:22 UTC, osherdp approved these changes

2021-12-14 13:05 UTC, merged