NO-ISSUE - Create random junit_xml report name
openshift/assisted-test-infra pull request #1299
Opened 2021-12-14 11:18 UTC by eliorerz

2021-12-14 11:19 UTC, eliorerz commented
/cc @osherdp

2021-12-14 13:05 UTC, osherdp requested changes

2021-12-14 13:05 UTC, osherdp commented on Makefile
> +UNITTES_JUNIT_FILE=$(shell mktemp -u "$(REPORTS)/unittest_XXXXXXXXX.xml")
*UNITTEST

2021-12-14 13:05 UTC, osherdp commented on Makefile
> +	JUNIT_FILE=$(mktemp "$(REPORTS)/unittest_XXXXXXXXX.xml") && JUNIT_REPORT_DIR=$(REPORTS) python3 ${DEBUG_FLAGS} -m pytest $(or ${TEST},discovery-infra/tests) -k $(or ${TEST_FUNC},'') -m $(or ${TEST_M
```suggestion
	JUNIT_FILE=$(mktemp "$(REPORTS)/unittest_XXXXXXXXX.xml") JUNIT_REPORT_DIR=$(REPORTS) python3 ${DEBUG_FLAGS} -m pytest $(or ${TEST},discovery-infra/tests) -k $(or ${TEST_FUNC},'') -m $(or ${TEST_MARKER},'') --verbose -s --junit-xml=$(UNITTES_JUNIT_FILE)
```

2021-12-14 16:07 UTC, eliorerz commented
![image](https://user-images.githubusercontent.com/16567084/146035191-61216d7b-03e4-4cfe-bcfe-925913b25579.png)
Works

2021-12-19 08:29 UTC, eliorerz commented
/retest

2021-12-19 08:34 UTC, osherdp approved these changes

2021-12-19 11:30 UTC, osherdp commented
/retitle MGMT-8549- Fix missing junit files on kube api tests

2021-12-19 11:42 UTC, merged