NO-ISSUE - Remove project path dependency from CI
openshift/assisted-test-infra pull request #1308
Opened 2021-12-16 12:39 UTC by eliorerz

2021-12-16 12:44 UTC, osherdp requested changes

2021-12-16 12:44 UTC, osherdp commented on Makefile
> +	TEST=./discovery-infra/tests/test_kube_api.py make test_parallel
blank line at end of file

2021-12-16 13:05 UTC, osherdp approved these changes

2021-12-17 14:58 UTC, osherdp commented
/hold
I think we already gave up for 2.3 test-infra based jobs, so no need to fix them anymore
Maybe we can even remove the relevant config file for this branch for test-infra repo

2021-12-17 16:36 UTC, eliorerz commented
@osherdp I agree. Let's delete the configuration file.

2021-12-19 08:27 UTC, closed without merging