MGMT-9555 - Add more complex triggers conditions comparison methods
openshift/assisted-test-infra pull request #1523
Opened 2022-03-09 16:37 UTC by eliorerz

Add the ability to not just activate trigger on "equal" condition, but also for more complex operations, e.g:

- not equal
- key in iterable

/cc @osherdp

2022-03-09 17:29 UTC, eliorerz commented
/retest

2022-03-10 13:53 UTC, eliorerz commented
/retest

2022-03-13 14:29 UTC, eliorerz commented
/retest

2022-03-13 16:18 UTC, eliorerz commented
/retest

2022-03-13 19:43 UTC, eliorerz commented
/retest

2022-04-07 13:20 UTC, osherdp requested changes

2022-04-07 13:20 UTC, osherdp commented on src/triggers/condition.py
> +class TriggerConditionType(Enum):
```suggestion
class TriggerConditionOperator(Enum):
```

2022-04-10 11:19 UTC, eliorerz commented on src/triggers/default_triggers.py
> +            Condition("remote_service_url", None, TriggerConditionType.NOT_EQUAL), worker_disk=consts.DISK_SIZE_120GB
I think you might be right, I'll remove that.

2022-04-10 12:01 UTC, osherdp approved these changes

2022-04-10 12:45 UTC, osherdp approved these changes

2022-04-10 19:37 UTC, merged