MGMT-9568: use client.update_host instead of update_hosts
openshift/assisted-test-infra pull request #1525
Opened 2022-03-10 11:17 UTC by danielerez

* Moved update_hosts from utils to day2_cluster.
* Used client.update_host instead of deprecated client.update_hosts.

2022-03-10 11:17 UTC, danielerez commented
/hold

2022-03-10 11:18 UTC, danielerez commented
/test ?

2022-03-10 11:18 UTC, danielerez commented
/test e2e-metal-assisted-day2

2022-03-11 12:42 UTC, danielerez commented
/test e2e-metal-assisted-day2

2022-03-13 07:52 UTC, danielerez commented
/test e2e-metal-assisted-day2

2022-03-13 07:52 UTC, danielerez commented
/cc @eliorerz 
/cc @osherdp

2022-03-13 09:03 UTC, danielerez commented
/test e2e-metal-assisted-day2

2022-03-13 09:21 UTC, osherdp requested changes

2022-03-13 09:21 UTC, osherdp commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +            libvirt_nodes -- A dictionary that may contain data about cluster hosts
We usually do:
```suggestion
        Args:
            client: An assisted service client
            cluster_id: ID of the cluster to update
            libvirt_nodes: A dictionary that may contain data about cluster hosts
```

2022-03-13 09:21 UTC, osherdp commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +
```suggestion
```

2022-03-13 09:21 UTC, osherdp commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +    def update_hosts(self, client, cluster_id, libvirt_nodes):
Please add type annotations

2022-03-13 09:25 UTC, danielerez commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +            libvirt_nodes -- A dictionary that may contain data about cluster hosts
right, just copy-pasted:) fixed

2022-03-13 09:25 UTC, danielerez commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +
done

2022-03-13 09:25 UTC, danielerez commented on src/assisted_test_infra/test_infra/helper_classes/day2_cluster.py
> +    def update_hosts(self, client, cluster_id, libvirt_nodes):
done

2022-03-13 09:26 UTC, osherdp approved these changes

2022-03-13 09:27 UTC, danielerez commented
/test e2e-metal-assisted-day2

2022-03-13 12:03 UTC, danielerez commented
/unhold

2022-03-13 12:08 UTC, danielerez commented
rebased

2022-03-13 12:09 UTC, danielerez commented
> 

rebased

2022-03-13 13:02 UTC, osherdp approved these changes

2022-03-13 13:40 UTC, merged