NO-ISSUE - Add client validation before running test suite
openshift/assisted-test-infra pull request #1541
Opened 2022-03-14 21:29 UTC by eliorerz

Validating that the client version exists on the assisted-service deployment is equal to the version that is used by out tests (installed in assisted-test-infra image)

Failure warning will be similar to:

```bash
2022-03-14 21:17:01,194 WARNING    - 139723800326400 - Mismatch client versions found! Version on assisted-service-54764b758b-78v9v=v2.1.0-132-g8c54328 != installed_version=v2.1.0-163-gfade32b
```

Note: It looks like that we always have mismatch versions (test-infra client is always more updated than the client on the service deployment)

/cc @osherdp

2022-03-15 08:42 UTC, osherdp commented
It's happening on CI? Or just on manual usage?

2022-03-15 08:43 UTC, osherdp commented
/test e2e-metal-assisted-onprem

2022-03-15 10:38 UTC, osherdp requested changes

2022-03-16 16:02 UTC, eliorerz commented on src/service_client/client_validator.py
> +        pass
Agreed

2022-03-16 17:24 UTC, eliorerz commented on src/service_client/client_validator.py
> +        time.sleep(5)
It's mainly for the local user. Is there any alternative for it?

2022-03-16 17:24 UTC, eliorerz commented on src/service_client/client_validator.py
> +        res = check_output([f"kubectl get pods -n {namespace} --output=json"], shell=True)
We need minikube kube-config file

2022-03-17 07:55 UTC, osherdp commented on src/service_client/client_validator.py
> +        res = check_output([f"kubectl get pods -n {namespace} --output=json"], shell=True)
it's not always on ``~/.kube/config``?

2022-03-17 07:57 UTC, osherdp commented on src/service_client/client_validator.py
> +        time.sleep(5)
we can add this kind of behavior to your new interactive client
but for any other use case we wouldn't want to sleep

2022-03-28 19:30 UTC, eliorerz commented on src/service_client/client_validator.py
> +def _get_service_container(namespace: str):
Not at the moment

2022-03-28 19:35 UTC, eliorerz commented on src/service_client/client_validator.py
> +        res = check_output([f"kubectl get pods -n {namespace} --output=json"], shell=True)
We run from inside the container

2022-03-28 19:36 UTC, eliorerz commented on src/service_client/client_validator.py
> +        time.sleep(5)
OK, removed it

2022-03-29 07:50 UTC, osherdp approved these changes

2022-03-29 07:50 UTC, osherdp commented on src/service_client/client_validator.py
> +        log.info(f"Failed to validate assisted-python-client version, {e}")
consider making it a warning log

2022-03-29 09:29 UTC, merged