MGMT-9691: Allow overriding hypershift control plane operator image
openshift/assisted-test-infra pull request #1546
Opened 2022-03-21 12:44 UTC by eranco74

MGMT-9691: CAPI e2e test is failing due to hypershift control plane operator image mismatch
 
 MGMT-9213: Add test_prepare_late_binding_kube_api_ipv4_highly_available to test_kube_api
 This can be used by capi test for setting up the env

* Save hypershift logs to file

2022-03-21 12:47 UTC, eranco74 commented
/test e2e-metal-assisted-capi

/hold

2022-03-21 12:58 UTC, osherdp requested changes

2022-03-21 12:58 UTC, osherdp commented on src/tests/test_kube_api.py
> +                    hypershift_CPO_image=os.environ.get("HYPERSHIFT_IMAGE", ""),
small preference for hypershift_cpo_image

2022-03-21 21:00 UTC, eranco74 commented
/test e2e-metal-assisted-kube-api-late-binding-single-node
/test e2e-metal-assisted-capi

2022-03-22 08:51 UTC, eranco74 commented
/test e2e-metal-assisted-capi

2022-03-22 10:11 UTC, eranco74 commented
/override ci/prow/e2e-metal-single-node-live-iso

2022-03-22 10:55 UTC, avishayt commented
/lgtm

2022-03-22 11:30 UTC, eranco74 commented
/unhold

2022-03-22 11:57 UTC, eranco74 commented
/test e2e-metal-assisted-kube-api-late-binding-single-node

2022-03-22 13:15 UTC, eranco74 commented
/override ci/prow/e2e-metal-assisted-capi

2022-03-22 13:54 UTC, eranco74 commented
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
Not related to changes in this PR

2022-03-22 14:06 UTC, merged

2022-03-24 14:04 UTC, eranco74 commented
/cherry-pick release-ocm-2.5