MGMT-10081: Log install progress
openshift/assisted-test-infra pull request #1548
Opened 2022-03-21 13:29 UTC by nmagnezi

2022-03-21 14:49 UTC, nmagnezi commented
/test e2e-metal-assisted-ocs

2022-04-04 09:58 UTC, nmagnezi commented
/retest-required

2022-04-24 09:01 UTC, nmagnezi commented
/test e2e-metal-assisted-cnv

2022-04-24 10:27 UTC, nmagnezi commented
Print looks okay. Example from R2-D2 logs:

2022-04-24 09:44:44,710 - root - INFO - 140372922790144 - cluster 1a4b91e0-c325-4d10-a4ee-9f8b29e86745 progress info: {'total_percentage': 87, 'preparing_for_installation_stage_percentage': 100, 'installing_stage_percentage': 100, 'finalizing_stage_percentage': 50}

2022-04-24 10:27 UTC, nmagnezi commented
/unhold

2022-04-24 10:51 UTC, eliorerz commented
/retest

2022-04-24 10:54 UTC, eliorerz requested changes

2022-04-24 10:54 UTC, eliorerz commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        log.info("starting to wait for builtin operators")
```suggestion
        log.info("Starting to wait for builtin operators")
```

2022-04-24 10:54 UTC, eliorerz commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        log.info("starting to wait for OLM operators")
```suggestion
        log.info("Starting to wait for OLM operators")
```

2022-04-24 10:54 UTC, eliorerz commented on src/assisted_test_infra/test_infra/utils/operators_utils.py
> +    log.debug("cluster %s info: %s", cluster_id, cluster)
```suggestion
    log.info("Cluster %s progress info: %s", cluster_id, cluster["progress"])
    log.debug("Cluster %s info: %s", cluster_id, cluster)
```

2022-04-24 11:41 UTC, nmagnezi commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        log.info("starting to wait for builtin operators")
Done

2022-04-24 11:42 UTC, nmagnezi commented on src/assisted_test_infra/test_infra/utils/operators_utils.py
> +    log.debug("cluster %s info: %s", cluster_id, cluster)
Done

2022-04-24 11:42 UTC, nmagnezi commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        log.info("starting to wait for OLM operators")
Done

2022-04-24 13:34 UTC, nmagnezi commented
/test e2e-metal-assisted-cnv

2022-04-25 06:12 UTC, nmagnezi commented
/test e2e-metal-assisted-cnv

2022-04-25 08:59 UTC, eliorerz approved these changes
LGTM

2022-04-25 10:34 UTC, merged