NO-ISSUE: Fixing capi test by adding label worker to minikube
openshift/assisted-test-infra pull request #1678
Opened 2022-06-08 16:59 UTC by tsorya

NO-ISSUE: Fixing capi test by adding label worker to minikube
In 4.11 ovn is a default network for hypershift cluster and it requires
worker label to run
NO-ISSUE: small improvements to case deploy scripts to cleanup
hypershift image locally before pulling

2022-06-08 17:12 UTC, osherdp requested changes

2022-06-08 17:12 UTC, osherdp commented on scripts/setup_capi_env.sh
> +kubectl get nodes minikube && kubectl label node minikube node-role.kubernetes.io/worker="" --overwrit
Shouldn't it be "overwrite"?

2022-06-08 18:35 UTC, tsorya commented on scripts/setup_capi_env.sh
> +kubectl get nodes minikube && kubectl label node minikube node-role.kubernetes.io/worker="" --overwrit
oops, copy pasted

2022-06-08 18:36 UTC, tsorya commented
/test ?

2022-06-08 18:36 UTC, tsorya commented
/test e2e-metal-assisted-capi

2022-06-08 18:37 UTC, eranco74 commented
/lgtm

2022-06-08 19:08 UTC, osherdp commented
/hold
Because otherwise nothing will wait for your optional test to finish

2022-06-08 20:22 UTC, tsorya commented
now there is another issue, container is stuck in creating

2022-06-08 21:14 UTC, tsorya commented
/retest

2022-06-09 07:37 UTC, eranco74 commented
/test e2e-metal-assisted-capi

2022-06-09 12:37 UTC, tsorya commented
/test e2e-metal-assisted-capi

2022-06-09 14:45 UTC, tsorya commented
/test e2e-metal-assisted-capi

2022-06-09 15:56 UTC, eranco74 reviewed
/lgtm

2022-06-10 04:02 UTC, eranco74 commented
/unhold

2022-06-10 04:04 UTC, merged