WIP: MGMT-9914: Integration of the ODF LVM operator with Assisted Ins…
openshift/assisted-test-infra pull request #1683
Opened 2022-06-13 10:01 UTC by dvachhan

This PR depends on [openshift/assisted-service#3921](https://github.com/openshift/assisted-service/pull/3921)

2022-06-13 12:26 UTC, osherdp commented
/uncc
@dvachhan please cc me again when you want me to review :)

2022-07-07 05:08 UTC, dvachhan commented
/test e2e-metal-assisted-cnv

2022-07-07 07:20 UTC, dvachhan commented
/test e2e-metal-assisted-ocs

2022-07-07 11:37 UTC, dvachhan commented
/assign @michaellevy101

2022-07-07 11:39 UTC, dvachhan commented
/cc @osherdp @rewantsoni @gobindadas

2022-07-07 11:44 UTC, osherdp commented
@dvachhan can you add a job so that we can see how it works?
for example: https://github.com/openshift/release/blob/b21f28ae0b8d8a04b296c0c973fab00280a07ffa/ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml#L260-L267

2022-07-07 11:47 UTC, osherdp requested changes

2022-07-07 11:47 UTC, osherdp commented on src/consts/olm_operators.py
> +                master_memory=1200,
just so I understand, those are additional resources that are required for the operator right?

2022-09-13 19:28 UTC, gamli75 approved these changes

2022-09-16 11:46 UTC, adriengentil approved these changes

2022-09-16 13:08 UTC, merged