Change the default disk size from 120GB to 100GB
openshift/assisted-test-infra pull request #1693
Opened 2022-06-15 18:09 UTC by osherdp

Since all product dependant places have been handled for the various
tasks under MGMT-9682, we can change the actual usage of it in our
tests.

/cc @osherdp 
/hold

2022-06-15 18:09 UTC, osherdp commented
/test e2e-metal-assisted-prod

2022-06-16 08:43 UTC, osherdp commented
/cc @eliorerz @paul-maidment

2022-06-16 08:53 UTC, eliorerz requested changes

2022-06-16 08:53 UTC, eliorerz commented on src/consts/resources.py
> +DEFAULT_MASTER_DISK: int = 100 * GB
```suggestion
DEFAULT_MASTER_DISK: int = DISK_SIZE_100GB
```

2022-06-16 09:30 UTC, osherdp commented on src/consts/resources.py
> +DEFAULT_MASTER_DISK: int = 100 * GB
Done!

2022-06-16 11:20 UTC, eliorerz approved these changes
LGTM

2022-06-16 11:29 UTC, merged

2022-06-22 11:12 UTC, osherdp commented
/cherry-pick release-ocm-2.5