Fix default value for getting vips
openshift/assisted-test-infra pull request #1807
Opened 2022-08-24 09:54 UTC by osherdp

Back in https://github.com/openshift/assisted-test-infra/pull/1797 I accidentally used the wrong non-compatible default value for those functions (we'd like them to behave like previously defined).

2022-08-24 10:06 UTC, osherdp commented
/hold
testing
/cc @eliorerz @lalon4

2022-08-24 11:23 UTC, osherdp commented
/test e2e-metal-assisted-ipv4v6

2022-08-28 09:30 UTC, eliorerz requested changes
Please change this also for `NutanixController`
https://github.com/openshift/assisted-test-infra/blob/master/src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py#L127

2022-08-28 09:33 UTC, eliorerz approved these changes
LGTM

2022-08-28 09:38 UTC, osherdp commented
/unhold

2022-08-28 13:11 UTC, merged