Allow injecting additional files in BIP test
openshift/assisted-test-infra pull request #1980
Opened 2023-01-09 10:41 UTC by vrutkovs

This would allow us to include promtail config to send bootstrap logs to Loki

2023-01-09 10:56 UTC, osherdp requested changes

2023-01-09 10:56 UTC, osherdp commented on src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
> +class wwBaseClusterConfig(BaseEntityConfig, ABC):
a mistype of some sort?

2023-01-09 10:56 UTC, osherdp commented on src/tests/test_bootstrap_in_place.py
> +    def inject_bootstrap(self, ignition_filename: string, butane_config: string):
afaik it needs to be:
```suggestion
    def inject_bootstrap(self, ignition_filename: str, butane_config: str):
```

2023-01-09 10:56 UTC, osherdp commented on src/tests/test_bootstrap_in_place.py
> +        if cluster_configuration.bip_butane_config:
can you show an example of such config?

2023-01-09 10:57 UTC, eranco74 commented on src/tests/test_bootstrap_in_place.py
> +        self.retrying_run_container(
This will merge the butane_config into the existing content of ignition_filename?
Seems to me that it will override it no?

2023-01-09 11:16 UTC, vrutkovs commented on src/assisted_test_infra/test_infra/helper_classes/config/base_cluster_config.py
> +class wwBaseClusterConfig(BaseEntityConfig, ABC):
oops, sorry, fixed

2023-01-09 21:02 UTC, osherdp commented
/retest

2023-01-10 10:02 UTC, osherdp approved these changes

2023-01-10 13:13 UTC, merged