Add timeout on wait_for_hosts_stage
openshift/assisted-test-infra pull request #2169
Opened 2023-05-23 11:41 UTC by iovadia

2023-05-23 11:44 UTC, iovadia commented
cc @eliorerz

2023-05-23 13:38 UTC, eliorerz requested changes

2023-05-23 13:38 UTC, eliorerz commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        interval=consts.DEFAULT_CHECK_STATUSES_INTERVAL,
```suggestion
        timeout: int = consts.CLUSTER_INSTALLATION_TIMEOUT // 2,
        interval: int = consts.DEFAULT_CHECK_STATUSES_INTERVAL,
```

2023-05-23 14:36 UTC, iovadia commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +        interval=consts.DEFAULT_CHECK_STATUSES_INTERVAL,
done, thanks

2023-05-23 16:04 UTC, iovadia commented on src/assisted_test_infra/test_infra/helper_classes/cluster.py
> +            interval=interval,
Done

2023-05-24 08:59 UTC, eliorerz approved these changes
LGTM

2023-05-24 09:04 UTC, merged