Add support to update iso file for set_boot_order
openshift/assisted-test-infra pull request #2216
Opened 2023-06-28 08:49 UTC by bkopilov

Added iso file path when user change the boot order. It will allow us in a cluster to boot nodes with different iso files uscases:
 - Day2 master must be in the same network as day1 masters, we can re-use one of the existing nodes to become a day2 master by overriding iso file
 - Static network changes requires to download the iso again but we dont want to override all nodes iso path
 - Validate re-download iso file when different configurations (proxy)
 - Add support for re-usable nodes plus check how we manage multiple iso in a cluster deployment

In case we want to re-use the node with same network params. node.set_boot_order(cd_first=True, cdrom_iso_path="/tmp/test.iso) node.start()

2023-06-28 08:52 UTC, bkopilov commented
@eliorerz   @lalon4  @talhil-rh @adriengentil

2023-06-28 10:09 UTC, adriengentil commented
/ok-to-test
/test ?

2023-06-28 10:10 UTC, adriengentil commented
/test e2e-nutanix-assisted 
/test e2e-metal-assisted-day2-arm-workers

2023-06-29 06:07 UTC, bkopilov commented
/retest

2023-06-29 09:22 UTC, adriengentil approved these changes
okay, it looks like the nutanix passed the boot order and failed later in the process.
late-binding and metal-assisted are failing for known flakes.

2023-06-29 18:35 UTC, eliorerz commented on src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
> +            source_file_element.setAttribute("file", cdrom_iso_path)
Please put it in a separate method

2023-06-29 18:36 UTC, bkopilov commented on src/assisted_test_infra/test_infra/controllers/node_controllers/libvirt_controller.py
> +            source_file_element.setAttribute("file", cdrom_iso_path)
ack.

2023-06-29 18:37 UTC, eliorerz commented
/lgtm cancel

2023-06-29 18:38 UTC, eliorerz commented on src/assisted_test_infra/test_infra/controllers/node_controllers/nutanix_controller.py
> +            raise NotImplementedError("set cdrom path not implemented for a node")
Not sure I understood this error message, Can you please improve it?

2023-06-29 18:39 UTC, eliorerz requested changes
/hold

2023-07-02 05:03 UTC, bkopilov commented on src/assisted_test_infra/test_infra/controllers/node_controllers/node_controller.py
> +    def set_boot_order(self, node_name, cd_first=False, cdrom_iso_path=None) -> None:
ack

2023-07-02 06:26 UTC, bkopilov commented
Hi Elior , 
There are many places in the code that annotation should be updated ... maybe in a seperate effort ? i changed related code to the fix

2023-07-02 14:54 UTC, eliorerz commented
> Hi Elior , There are many places in the code that annotation should be updated ... maybe in a seperate effort ? i changed related code to the fix

I know, our approach on that is if we touch some code that is not annotated we add the annotation in the relevant PR. anyway, we usually not blocking PRs on those stuff.

2023-07-02 14:55 UTC, eliorerz commented
/retest

2023-07-02 14:55 UTC, eliorerz commented
/test e2e-vsphere-assisted e2e-nutanix-assisted-4.13

2023-07-02 14:56 UTC, eliorerz approved these changes
LGTM

2023-07-02 21:54 UTC, eliorerz commented
/retest

2023-07-03 05:48 UTC, eliorerz commented
/override ci/prow/e2e-metal-assisted-ipv4v6 
Doesn't seem to be related to the failure

2023-07-03 05:48 UTC, eliorerz commented
/unhold

2023-07-03 05:51 UTC, merged