NO-ISSUE: add ability to configure minikube
openshift/assisted-test-infra pull request #2342
Opened 2023-12-24 07:57 UTC by eifrach

* Add ability to configure minikube setup
* allows to change all minikube configuration using env values
*  default setup has not change

2023-12-24 10:02 UTC, gamli75 commented
Few remarks:
1. can you check why you have all those space/ tab changes? it's complicated to follow the real changes 
2. can you add why we need to configure minikube? what do we want to solve?

2023-12-24 11:13 UTC, eifrach commented
>  can you check why you have all those space/ tab changes? it's complicated to follow the real changes

The tab are from my IDE linter. I can fix it.

> can you add why we need to configure minikube? what do we want to solve?

so this is mostly for beaker lab where you dont have enoguh space in the default location.
since I've  add this variable, I figured best to move all the param as well so we can change them if needed.

2024-01-02 09:02 UTC, adriengentil commented
No need to specify the variables [here](https://github.com/openshift/assisted-test-infra/blob/master/skipper.env) to pass them to skipper env?

2024-01-15 13:18 UTC, eifrach commented
/cc @osherdp 
/cc @adriengentil

2024-01-15 18:06 UTC, osherdp requested changes

2024-01-15 18:06 UTC, osherdp commented on README.md
> +| `MINIKUBE_REGISTRY`| set registry image, default = "quay.io/libpod/registry:2.8" |
just for some extra clarity
```suggestion
| `MINIKUBE_REGISTRY_IMAGE`| set registry image, default = "quay.io/libpod/registry:2.8" | 
```

2024-01-15 18:06 UTC, osherdp commented on scripts/hub-cluster/minikube.sh
> +        minikube start --force --wait-timeout=15m0s  || true
so where do we use all the `MINIKUBE_*` values?

2024-01-16 18:15 UTC, osherdp commented on scripts/hub-cluster/minikube.sh
> +        minikube start --force --wait-timeout=15m0s  || true
Oh, missed that
Thanks for the explanation!

2024-01-16 18:15 UTC, osherdp approved these changes

2024-01-16 19:46 UTC, merged