Add natsort package to requirements.txt
openshift/assisted-test-infra pull request #2417
Opened 2024-05-01 19:49 UTC by bkopilov

The package allows us to sort complicated versions with numbers and naming. Using this package in custom ocp tests, getting a list of versions and sorting for last element .

2024-05-02 05:13 UTC, bkopilov commented
@adriengentil , @danmanor

2024-05-02 07:03 UTC, danmanor commented
@bkopilov Why do you add the package but not use it ?

2024-05-02 07:03 UTC, danmanor commented on requirements.txt
> +natsort
We need the exact version

2024-05-02 07:07 UTC, bkopilov commented
> @bkopilov Why do you add the package but not use it ?

I am using it in kni-assisted-installer-auto tests which run from podman containers.

2024-05-02 07:29 UTC, danmanor commented
@bkopilov I don't understand, it is not used in this repo, so why add it here ?

2024-05-02 08:06 UTC, bkopilov commented
> @bkopilov I don't understand, it is not used in this repo, so why add it here ?

Because here we controll what pip packages are installed on build image.
Dockerfile.assisted-test-infra

> RUN pip3 install --upgrade pip && \
>       pip3 install --no-cache-dir -I -r ./requirements.txt -r ./requirements-dev.txt && \
>       pip3 install --upgrade /build/pip/*

2024-05-02 08:22 UTC, danmanor commented
I mean why not add it to `kni-assisted-installer-auto`  ?

2024-05-02 08:47 UTC, danmanor commented
/ok-to-test

2024-05-02 10:48 UTC, bkopilov commented
/retest

2024-05-08 09:30 UTC, eliorerz commented
> I mean why not add it to `kni-assisted-installer-auto` ?

I agree, if it's not used in test-infra I think the best it to add it as a dependency to `kni-assisted-installer-auto`

2024-05-08 13:46 UTC, bkopilov commented
> > I mean why not add it to `kni-assisted-installer-auto` ?
> 
> I agree, if it's not used in test-infra I think the best it to add it as a dependency to `kni-assisted-installer-auto`

Hi , 
the kni-assisted-installer run from the container (Centos9) the package is part of pip installation on the container.
The Dockerfile.assisted-test-infra running the requirements.txt installation .

How can i install the python package from KNI ? 
Do you mean 
import pip 
pip.main(['install', "natsort"])

2024-05-28 07:32 UTC, bkopilov commented
> > > I mean why not add it to `kni-assisted-installer-auto` ?
> > 
> > 
> > I agree, if it's not used in test-infra I think the best it to add it as a dependency to `kni-assisted-installer-auto`
> 
> Hi , the kni-assisted-installer run from the container (Centos9) the package is part of pip installation on the container. The Dockerfile.assisted-test-infra running the requirements.txt installation .
> 
> How can i install the python package from KNI ? Do you mean import pip pip.main(['install', "natsort"])

@eliorerz , @lalon4  , Not sure how can i force this package from kni tests , the image docker set by you before we run kni ... and i must update the container package where the code runs from ?

What do you suggest  ?  the make action is from test-infra...  should i call to pip from KNI ?

2024-05-29 11:41 UTC, eliorerz commented
> > > > I mean why not add it to `kni-assisted-installer-auto` ?
> > > 
> > > 
> > > I agree, if it's not used in test-infra I think the best it to add it as a dependency to `kni-assisted-installer-auto`
> > 
> > 
> > Hi , the kni-assisted-installer run from the container (Centos9) the package is part of pip installation on the container. The Dockerfile.assisted-test-infra running the requirements.txt installation .
> > How can i install the python package from KNI ? Do you mean import pip pip.main(['install', "natsort"])
> 
> @eliorerz , @lalon4 , Not sure how can i force this package from kni tests , the image docker set by you before we run kni ... and i must update the container package where the code runs from ?
> 
> What do you suggest ? the make action is from test-infra... should i call to pip from KNI ?

I think that the best approach here is to add another step during kni-auto test-infra image build process, then build a `qe-test-infra` image using a new Dockerfile with all the dependencies you need.

2024-05-30 07:07 UTC, bkopilov commented
@eliorerz , Ok . i will close it and move the logic to kni-test-infra

2024-05-30 07:08 UTC, bkopilov commented
Moving the logic to kni-test

2024-06-06 06:38 UTC, eliorerz requested changes

2024-06-06 06:38 UTC, eliorerz commented on requirements.txt
> +natsort==8.4.0
```suggestion
natsort==8.4.0  # natsort used in kni-assisted-installer-auto
```

2024-06-14 06:09 UTC, bkopilov commented
/retest

2024-06-14 06:29 UTC, bkopilov commented
/retest

2024-06-24 11:17 UTC, eliorerz commented
/retitle NO-ISSUE: Add natsort package to requirements.txt

2024-06-24 11:18 UTC, eliorerz approved these changes
LGTM

2024-06-24 13:17 UTC, merged