MGMT-3474 - Add e2e test to oc must-gather
openshift/assisted-test-infra pull request #399
Opened 2021-01-07 08:05 UTC by slaviered

2021-01-07 08:05 UTC, slaviered commented
/assign @ybettan

2021-01-07 08:28 UTC, YuviGold requested changes
Apparently a bad rebase.
* `openshift_version` was added.
* `cluster_machince_cidr` should be called from the `controller`.
* `set_hostnames` should be called to fix IPv6 hostnames.

2021-01-07 10:13 UTC, lalon4 commented on discovery-infra/test_infra/helper_classes/cluster.py
> +    def wait_for_non_bootstrap_masters_to_reach_joined_state_during_install(self):
Why not making this method more generic by calling it `wait_for_hosts_to_reach_joined`, and accept `nodes_count` as a parameter?

2021-01-10 08:53 UTC, lalon4 commented
/lgtm

2021-01-10 09:28 UTC, YuviGold approved these changes

2021-01-10 09:29 UTC, slaviered commented
/assign @ybettan

2021-01-10 10:46 UTC, merged