MGMT-4100 Move download logs logic to download_logs.sh script
openshift/assisted-test-infra pull request #523
Opened 2021-02-15 14:30 UTC by YuviGold

Support onprem and k8s logs with getting ADDITIONAL_PARAMS environment variable. i.e. --must-gather, --download-all, --update-by-events.

Add `suppressLog` to suppress an exception but still log it

/cc @osherdp

2021-02-15 14:38 UTC, osherdp commented on discovery-infra/logger.py
> +class suppressLog(suppress):
it's a misleading name, I thought it just suppresses logging inside the block
Maybe ``suppressAndLog`` or ``suppressButLog``? Or ``suppressWithNotification``/``WithLogging``

2021-02-15 14:39 UTC, osherdp requested changes
just the class name sounds weird

2021-02-15 15:12 UTC, YuviGold commented
I divided this PR into another PR https://github.com/openshift/assisted-test-infra/pull/524

2021-02-15 15:25 UTC, osherdp approved these changes
/lgtm

2021-02-15 21:48 UTC, YuviGold commented
/retest

2021-02-16 07:39 UTC, osherdp commented
@YuviGold all latest failures:
```
HTTP response body: {"code":"500","href":"","id":500,"kind":"Error","reason":"coreos-installer failed: /data/coreos-installer: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory\n: exit status 127"}
```

Not relevant at all to your changes, which makes me think it's somehow got broken

2021-02-16 09:44 UTC, YuviGold commented
/retest

2021-02-16 10:39 UTC, merged