Fix operator status when waiting for operator to finish
openshift/assisted-test-infra pull request #708
Opened 2021-04-18 18:30 UTC by lalon4

2021-04-18 18:32 UTC, lalon4 commented
/hold

2021-04-19 06:49 UTC, osherdp commented
@lalon4 can you add some description?

2021-04-19 07:02 UTC, osherdp requested changes

2021-04-19 08:08 UTC, lalon4 commented on discovery-infra/test_infra/utils.py
> +        new_statuses.append(consts.OperatorStatus.FAILED)
Thanks Osher for the suggestions. When ran this code then i noticed that the statuses are aggregated during the waiting. i.e:
`2021-04-18 22:12:26,440 INFO       - 140343419444096 - Asked operators to be in one of the statuses from ['available', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed', 'failed'`

So i am testing another suggestion. LMK what you think

2021-04-19 08:13 UTC, osherdp requested changes

2021-04-19 08:13 UTC, osherdp commented on discovery-infra/test_infra/helper_classes/cluster.py
> +        if not fall_on_error_status:
just ``else``

2021-04-19 08:45 UTC, lalon4 commented
/cc @nshidlin

2021-04-19 09:15 UTC, osherdp approved these changes

2021-04-19 10:36 UTC, lalon4 commented
/unhold

2021-04-19 10:52 UTC, merged