MGMT-6417- Deprecate deploy_nodes Makefile target
openshift/assisted-test-infra pull request #897
Opened 2021-06-20 13:48 UTC by eliorerz

2021-06-20 16:34 UTC, eliorerz commented
/retest

2021-06-21 06:09 UTC, YuviGold commented on discovery-infra/targets/target.py
> +def get_api_client(namespace: str, remote_service_url: str, offline_token=None, **kwargs) -> InventoryClient:
Merge with conftest
https://github.com/openshift/assisted-test-infra/blob/28ca2b0b281e10dda55a6849c69cf4c4bfa10a6f/discovery-infra/tests/conftest.py#L99-L106

2021-06-21 06:09 UTC, YuviGold commented on discovery-infra/targets/deploy_nodes.py
> +import argparse
Make executable with shabang

2021-06-21 10:52 UTC, eliorerz commented
/uncc @romfreiman @gamli75

2021-06-21 10:52 UTC, eliorerz commented
/cc @tsorya @oshercc @YuviGold

2021-06-21 10:53 UTC, eliorerz commented
/uncc @oshercc 
/cc @osherdp

2021-06-21 11:22 UTC, eliorerz commented
/retest

2021-06-22 09:43 UTC, osherdp requested changes
partial review

2021-06-22 09:43 UTC, osherdp commented on Makefile
> +	skipper make $(SKIPPER_PARAMS) _deploy_nodes ADDITIONAL_PARAMS="-i"
maybe use the longer version of ``-i`` option, to have it easier to understand

2021-06-22 09:43 UTC, osherdp commented on discovery-infra/targets/deploy_nodes.py
> +class DeployNodesWithInstall(DeployNodes):
I don't know what I feel about those levels of inheritance and about transforming makefile concepts to python classes
I of course agree with the need to simplify our code, just not sure about the proposed solution

2021-06-22 09:43 UTC, osherdp commented on discovery-infra/targets/deploy_nodes.py
> +    parser.add_argument("-i", "--install", help="Install flag", type=bool, nargs='?', default=False, const=True)
please don't write ``Install flag``, I'm not presenting myself as "Osher some kind of human being" :)

2021-06-22 09:43 UTC, osherdp commented on discovery-infra/targets/deploy_nodes.py
> +        DeployNodes().run()
again, it's hard to my eyes
if using inheritance then at least use polymorphism

2021-06-22 16:45 UTC, osherdp requested changes
full review

2021-06-22 16:45 UTC, osherdp commented on discovery-infra/test_infra/factory.py
> +def nodes_factory(config: TerraformConfig, nat: NatController):
I remember us having a similar code, no?
Or maybe it just creates the controller and not Nodes

2021-06-22 17:38 UTC, tsorya commented
@osherdp @YuviGold @eliorerz to say the truth i thought that the idea is to use 100% same logic as with tests.
I am not sure why we need different logic for running specific target, it is duplication of the test from my point of view.
We can have generic test with support of envs or we can have test per target but i don't think we need another code that we have already in test.  
make deploy_nodes -> make test TEST=deploy_nodes or make test TEST=generic DONT_INSTALL=True ...
What do you think?

2021-07-28 14:43 UTC, eliorerz commented
This PR replaced with https://github.com/openshift/assisted-test-infra/pull/990

2021-07-28 14:43 UTC, closed without merging